name: Deploy to Amazon Lambda Production Techgrowth Labs

on:
  push:
    branches:
      - master

env: # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }} # set this to your Amazon ECR repository name]

  LAMBDA_FUNCTION_NAME: ${{ vars.LAMBDA_FUNCTION_NAME }}

  AWS_REGION: ${{ vars.AWS_REGION }}

  APP_NAME: ${{ vars.APP_NAME }}

  S3_BUCKET: ${{ vars.S3_BUCKET }}

  P12_CERT: ${{ vars.P12_CERT }}

permissions:
  contents: read
  packages: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: TECHGROWTH_LABS_PRD

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build AWS Lambda
        id: build-aws-lambda
        run: |
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          aws ssm get-parameters --region ${{vars.AWS_REGION}} --names /prd/$APP_NAME --query 'Parameters[*].Value' --output text > .env
          aws s3 cp s3://$S3_BUCKET/$P12_CERT $P12_CERT
          ls -la
          npm ci
          npm run build

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: latest
        run: |
          docker build --build-arg GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}} -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "::set-output name=IMAGE_URI::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Deploy Lambda Function
        run: |

          # Update the Lambda function code with the ECR image
          aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --image-uri ${{ steps.build-image.outputs.IMAGE_URI }}
